### ISSUE TITLE
v86.wasm not found

### ISSUE THREAD

**Issue by upsetbit** [oldweb-today/oldweb-today#2]
_Thank you for putting the time and effort into this project!_

When running locally, I couldn't try any emulator that uses Windows. Looking at the browser inspector, the GET call for `/dist/v86.wasm` returned a 404. I've simply downloaded the file from the site (https://oldweb.today/dist/v86.wasm), putted inside `dist` and everything worked just fine.

To build the project I've cloned the repo and run `yarn install`. I am missing some step here? I couldn't find any info about this file (`v86.wasm`) on the README page.

On some minor note, I've noted that some icons are also missing (`firefox.png`, `opera.png` and `linux.png`).

**Comment by ikreymer** [comment]
Added the missing files, should now be fixed on main
