### ISSUE TITLE
emulated windows browsers not loading/dns errors

### ISSUE THREAD

**Issue by earthlingplant** [oldweb-today/oldweb-today#3]
Hi there! Would like to preface this by saying this project is really amazing and has led me to dig into a lot of old websites lately, so thank you! 
I noticed that, when I updated chrome last night, I would always receive an error when I tried to load up an old geocities page. I tried it on the other browsers (including ruffle) and it worked quite well. I think this might(?) be due to the chrome update itself and not the emulation and all that. If this error isn't just on my end, it can reproduced by using Navigator (windows, IE 5, or IE 6  on chrome with the latest update. For some reason, even the default geocities archive that loads with a new oldweb.today tab will not work.
![Screen Shot 2022-02-12 at 5 09 47 PM](https://user-images.githubusercontent.com/99564065/153784746-dd422057-d1cb-4e70-af12-3dea2415765f.png)
![Screen Shot 2022-02-13 at 7 18 43 PM](https://user-images.githubusercontent.com/99564065/153784797-faa73524-3e48-4be3-b99f-0129c8e15320.png)

**Comment by earthlingplant** [comment]
(ignore the burgerking.com one lol,,, my friend has been researching some info about the "BK Kids Club" so I tried to find some stuff for them)

**Comment by ikreymer** [comment]
Hopefully should be fixed now, reopen if you see persistent issues.
