### ISSUE TITLE
Stuck on infinite downloading screen

### ISSUE THREAD

**Issue by TheSystemGuy1337** [oldweb-today/oldweb-today#5]

**Comment by TheSystemGuy1337** [comment]
Nobody has responded. This is proof that oldweb.today is dead. Fork it while you still can.

**Comment by ikreymer** [comment]
The service is being rate-limited by Cloudflare, and I haven't had time to look into it, or move to another service :/
The code isn't going anywhere of course

**Comment by TheSystemGuy1337** [comment]
I hosted it myself on localhost and had the same problem. It could be the IA is intentionally blocking oldweb.todays IP address. If Cloudflare was really limiting it, I would be running into artificial HTTP 500 errors

**Comment by ikreymer** [comment]
oldweb.today should be fixed now! It has been moved off of cloudflare (except for CORS) proxy, hosted entirely via GitHub pages + images on a DigitalOcean bucket

**Comment by TheSystemGuy1337** [comment]
Just tried it. It just hangs on “Loading, please wait”

**Comment by TheSystemGuy1337** [comment]
Tried it again. The glorious service is finally back. Also ran CON/CON and didn’t get the actual BSOD
